### ISSUE TITLE
Multi-Valued Items in a Field

### ISSUE THREAD

**Issue by gth843d** [nicolaskruchten/pivottable#1172]
This is just a basic example but is it possible to handle multi valued items within a given field?

`[{"Rec":"1403","Lucky Numbers":"5","Lucky Numbers":"19","Lucky Numbers":"21","Lucky Numbers":"14"},{"Rec":"1402","Lucky Numbers":"5","Lucky Numbers":"7","Lucky Numbers":"19","Lucky Numbers":"21","Lucky Numbers":"33","Lucky Numbers":"17","Lucky Numbers":"14"}]`

Trying with arrays for each "Rec" instead created an item in the table like "5,19,7" instead of adding them like I hoped.

Any help is appreciated.

**Comment by nicolaskruchten** [comment]
Unfortunately this is not possible, no. I should add that `{"Rec":"1403","Lucky Numbers":"5","Lucky Numbers":"19","Lucky Numbers":"21","Lucky Numbers":"14"}` isn't actually a valid Javascript object, because Javascript itself doesn't support repeated keys. It will actually evaluate to the same thing as `{"Rec":"1403","Lucky Numbers":"14"}`

You'll have to "unpivot" this data first and have one row of input per `Rec`/`Lucky Numbers` pair.

**Comment by gth843d** [comment]
Got it, thanks. I was able to get it to work by doing as you said and then using the Unique function to total the unique record numbers.
