### ISSUE TITLE
Is it possible to show Geo Location Charts ????  

### ISSUE THREAD

**Issue by kumar31rajesh** [nicolaskruchten/pivottable#258]
Hi Nicolas,
I am using your pivottable  library and its very fantastic .Your library provide functions to create line,bar ,table,HeatMap charts is it possible to create Geo Maps using your library if yes can you tell me how i can show Geo Map for location based data using your library ????? \
![image](https://cloud.githubusercontent.com/assets/5661805/5471621/dca59efa-861d-11e4-9d07-b6453e4b0637.png)

I tryed with my sample data but whenever i tryed to select the map its showing error.

**Comment by LittleHamster** [comment]
@nicolaskruchten 
may I know how come geo maps are not compatible?
in my csv I have a country row and some data which I want to show on the map
the data format looks very similar to what Google is showing, thanks

**Comment by nicolaskruchten** [comment]
@LittleHamster please create new issues rather than commenting on old ones, as the latter generates notifications to everyone on the thread.

To answer your question, as I stated above the *output* of PivotTable.js' aggregation cannot match the inputs required by Google Charts' geo types, regardless of what your input CSV might look like.
