### ISSUE TITLE
Shown 'opts.vals' in dropdown not 'shownAttributes'

### ISSUE THREAD

**Issue by gdevilee** [nicolaskruchten/pivottable#264]
The vals dropdown shows the 'shownAttributes' not the 'opts.vals'
line 1127-1128:

                for (_n = 0, _len4 = opts.vals.length; _n < _len4; _n++) {   // for (_n = 0, _len4 = shownAttributes.length; _n < _len4; _n++) {
				  attr = opts.vals[_n];									     // attr = shownAttributes[_n];

**Comment by nicolaskruchten** [comment]
This is no a bug: the values of the dropdown are meant to be the available options, not the settings of `opts.vals`.

**Comment by gdevilee** [comment]
Why there is an option for opts.vals in parameters?
Not all the available options can be used for vals (only numeric).

In an earlier version there was a separate option for Vals.

**Comment by nicolaskruchten** [comment]
I believe you have misunderstood this parameter, which has not changed in behaviour since the first verion. I have just updated the example here http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html to show how you can use the `vals` parameter. It serves not to determines which options are *available* in the dropdown(s) but which option(s) are *selected* upon render.

**Comment by gdevilee** [comment]
I have 10 fields to display. Only 2 of them are numeric. The rest gives empty results in the matrix.
May be it's an idea to limit the val-list to just a selection of the fields.
The user can then only select valid numeric fields.

**Comment by nicolaskruchten** [comment]
The thing is that not all aggregators operate only on numeric data. `unique`, for example, can operate on string data. There is an issue open already about type-hinting, which, depending upon the implementation, would address your concerns: #191
