### ISSUE TITLE
mps_csv.html (Demo loaded from csv) fails with a blank screen in standalone mode

### ISSUE THREAD

**Issue by legrandlegrand** [nicolaskruchten/pivottable#275]
Hello,

Thanks for this very great tool !

I would like to use it in Google Chrome / windows 7 connected with our query builder, that should generate csv local files.

It works with local.html (Demo from local CSV) but fails with mps_csv.html (Demo loaded from csv) with a blank screen and message :
 XMLHttpRequest cannot load file:///C:/Users/xxxxx/tools/pivottable-1.3.0/examples/mps.csv. Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, https, chrome-extension-resource.

Thanks in advance
Regards
PAscal

**Comment by nicolaskruchten** [comment]
The problem is pretty much exactly what the error says: browsers do not let you load files not being served by HTTP using XMLHttpRequest. In order for the `$.getJSON()` call to work, files *must* be served by an HTTP server, not opened directly from disk. So if you're on Windows you need to run IIS or a local Apache or Nginx or you need to call `python -m SimpleHTTPServer` in the examples directory (all ways of running a local HTTP server) and then point your browser to http://localhost:<PORT>/ and everything will work :)

**Comment by legrandlegrand** [comment]
Thanks,
local.html works fine in standalone mode (without any HTTPserver), I will modify it for our needs.

**Comment by nicolaskruchten** [comment]
OK. Can we close this issue or are there any further questions about this? :)

**Comment by legrandlegrand** [comment]
Yes we can. Thanks Again
