### ISSUE TITLE
return table

### ISSUE THREAD

**Issue by yuli06** [nicolaskruchten/pivottable#293]
hi I´m traying to get a table by return instead of see it in the browser, I´ve explored the code and saw in the pivot.js file, which I´m using, there is a function called  "pivotTableRenderer" where creates the table and then in line #805 start a function that is called when we make the pivot table and it´s which return the table to the browser, I´m not sure if this is correct, but in this way I want to return the table structure not the visual table, could you give and advise?
(if I could get the table and also it can be seen in the browser that would be perfect)
thanks

**Comment by nicolaskruchten** [comment]
`pivot()` creates a `PivotData` object and then calls a renderer on it. You can write your own renderer which does something else with the `PivotData` object if you like...

**Comment by yuli06** [comment]
hi again thanks for your answer, it clarified me the things I studied the code and understood more, but I have a question at the end of the pivot function you return "something" with this code "return this.append(result);", what reference the object this that us in this line??

**Comment by nicolaskruchten** [comment]
The object being returned is a jQuery object. This is standard practice for jQuery plugins: they return the object on which they were called. So from `pivot()` and `pivotUI()` we want to return `this`. But as it appens, `this.append()` also returns `this` because `append()` is a jQuery function. So we can return `this.append()` and the right thing happens.
