### ISSUE TITLE
Filter dropdown not visible (on some Android browsers)

### ISSUE THREAD

**Issue by JohnAG** [nicolaskruchten/pivottable#298]
Hi.
I'm testing this demo: http://nicolas.kruchten.com/pivottable/examples/fully_loaded.html
When I run this demo in chrome on my desktop it works perfect.
But when I try the same demo in chrome in my Android mobile device the filter dropdown is not visible.

Regards
JohnA

![screenshot_2015-02-17-21-45-32](https://cloud.githubusercontent.com/assets/5116251/6236924/e0a07712-b6ee-11e4-8d33-7295e521029e.png)

**Comment by nicolaskruchten** [comment]
Interesting. Any details on the Android and Chrome version? I'll need to hunt down a device to try it. I suspect it's something silly like the device doesn't support the triangle glyph or something...

**Comment by JohnAG** [comment]
It's a Sony Xperia Z1 running Android version 4.4.4
Chrome version 40.0.2214.109

Same issue with Dolphin browser version 11.3.8

With firefox for Android it works but the dropdown arrow does not look particulary good
![screenshot_2015-02-17-23-05-11](https://cloud.githubusercontent.com/assets/5116251/6238227/98432cca-b6f9-11e4-87c4-de1e61585595.png)

**Comment by nicolaskruchten** [comment]
Hmmm. Can you try to replace `&#x25BE;` in the pivot table code with a different triangle encoding like `&#9662;` or otherwise some normal character like `*` and see if that appears in all the browsers you need to be able to use? If so, it just means that the browsers you're using can't render the little downward triangle glyph, which is a bummer but I can probably find a workaround.

Another possible problem is the font you're using... what font is it in these pages? Can you try something like Verdana?

**Comment by JohnAG** [comment]
I'm testing this demo http://nicolas.kruchten.com/pivottable/examples/fully_loaded.html
I'm thinking of using the pivottable in an cordova application for mobile devices, 
When I get to the point where I do actual (code) tests with the pivottable, I will try your fixes

thanks
JohnA
