### ISSUE TITLE
PivotTable is frozen after save HTML as 

### ISSUE THREAD

**Issue by legrandlegrand** [nicolaskruchten/pivottable#299]
Hello,
We have developped and interface in our SQL tool to export results of SQL queries in an HTML page using PivotTable.

Our problem is that after 
- opening the demo page
- moving columns, changing filters, changing rendering
- saving the page as a new page
- opening the saved page
- user modifcations first appear
- and then display is reset to initial pivot table (and looses user modifications).
- saved pivot table can be used

Note that saving 
http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html as a new html file, keeps user rendering modifications but with a "frozen" PivotTable

Is it possible to save user rendering and keep PivotTable usable without having to save configuration manually as explained in
http://nicolas.kruchten.com/pivottable/examples/onrefresh.html
? 

Here is our html page code:
```
<!DOCTYPE html>
<html>
	<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Pivot Demo</title>
        <link rel="stylesheet" type="text/css" href="./PivotDemo_files/pivot.css">
		<script type="text/javascript" src="./PivotDemo_files/jsapi"></script>
        <script type="text/javascript" src="./PivotDemo_files/jquery-1.8.3.min.js"></script>
        <script type="text/javascript" src="./PivotDemo_files/jquery-ui-1.9.2.custom.min.js"></script>
        <script type="text/javascript" src="./PivotDemo_files/pivot.js"></script>
		<script type="text/javascript" src="./PivotDemo_files/gchart_renderers.js"></script>
        <style>
            * {font-family: Verdana;}
        </style>
		
    </head>
    <body>
        <h3>Pivot demo with preloaded data.</h3>
		<div id="output" style="margin: 10px;"></div>
        <br>
		
		<div style="display:none">
        <h3>Input table:</h3>
		<script src="pivotInputTable.js"></script>
		</div>
		
		<script type="text/javascript">
			google.load("visualization", "1", {packages:["corechart", "charteditor"]});
            $(function(){
				var derivers = $.pivotUtilities.derivers;
                var renderers = $.extend($.pivotUtilities.renderers, 
                    $.pivotUtilities.gchart_renderers);

				var input = $("#input");
                $("#output").pivotUI(input, {
					renderers: renderers
				}
				);
             });
        </script>
	</body>
</html>
``` 

pivotInputTable.js:
``` 
document.write('<table id="input" border="1">')
document.write('<thead><tr>')
document.write('<th>id</th><th>SRC1</th><th>TGT1</th>')
document.write('</tr></thead>')
document.write('<tbody>')
document.write('<tr><td>1</td><td>1</td><td></td></tr>')
document.write('<tr><td>1</td><td></td><td>1</td></tr>')
document.write('</tbody></table>')
```

**Comment by nicolaskruchten** [comment]
There are a few things happening here:

1. When you use File > Save as... what you get (in Chrome, at least) is a full serialization of the DOM, so the pivot table you first see is what was saved. What then happens is that the Javascript runs and overwrites the table with the newly-rendered, non-customized table.

2. The demos all work with `$.getJSON()` to load the data, which will not work if you try to load a local file (browsers do not support this kind of request for file:/// requests). This means that the first part of the above point works (the table is rendered) and the second fails (check your Javascript console, you'll see that `pivotUI()` is not actually called due to the failure of `$.getJSON()`)

In general, then, this is going to be quite tricky to make work with just the browser's Save-as functionality and you will have to find a way to store the user settings JSON object somewhere in the DOM and get the saved file to use that if present.

**Comment by legrandlegrand** [comment]
We don't use JSON as we store data as a table, but this is not changing the fact that we won't be able to simply use the browser save-as functionality ...
Thanks for you answer and for PivotTable.js

**Comment by nicolaskruchten** [comment]
Oh I meant the JSON settings which are passed back to you in the `onRefresh` callback. If you store those in the DOM somewhere and have the Javascript use those settings if present, you may be able to use Save-as after all...
