### ISSUE TITLE
Option to move "grand total" row from the bottom to the top?

### ISSUE THREAD

**Issue by LukePivot** [nicolaskruchten/pivottable#352]
Hi Nicolas,

Your library is amazing.  It's been really incredible playing around with what it can do and implementing it into our solution.  

One of my users suggested something that makes sense, but I wanted to float it to you to see if you'd consider it:

For the grand total row that always appears at the bottom, could you add an option to have it show up at the top as the first row below the headers row?  Reason being is that this grand total row is important a lot of times, and if you have a long pivot you have to scroll all the way to the bottom to see it.  

Having an option to default this grand total row to the top would be very useful, in my opinion.  We would definitely default it to that option if there was a choice.

Thanks a lot for your consideration on this and keep up the great work!

**Comment by nicolaskruchten** [comment]
I'm glad this tool is useful for you!

I don't think I would implement this feature request as an option into the main library (this is the first time anyone has requested it), but there are a couple of ways you can get this behaviour.

1. you could maintain a copy of the `pivotTableRenderer()` function in a separate file and use that renderer instead of the builtin one (similar to how the c3_renderers are in their own file). 
1. you could modify the builtin `pivotTableRenderer()` function.

I recommend the first option, to make it easier to upgrade to newer versions of the library later.

In either case, you want to take the block of code in `pivotTableRenderer()` between the comments `finally, the row for col totals, and a grand total` and `squirrel this away for later ` and move it above the comment `now the actual data rows, with their row headers and totals`.

**Comment by LukePivot** [comment]
Thanks a ton for the response, Nicolas.

I just looked at the pivotTableRenderer function on the pivot.js file that was part of the package we downloaded, and those comments you referenced aren't listed in the function, unfortunately.

I'd love to try out your suggestion and move the block of code to the right spot, but I have no point of reference within the function itself.  If it's not a pain, could you maybe paste the block of code you want me to try moving and just tell me the spot where it should be moved to?   Again, thanks a ton for any help on this.

**Comment by nicolaskruchten** [comment]
The comments are in the `pivot.coffee` file, which you can modify and recompile... If that's not something you want to do, can you confirm that you're using the latest version of pivot.js (i.e. this one: https://github.com/nicolaskruchten/pivottable/blob/master/dist/pivot.js ?) and I can give you line numbers.

**Comment by LukePivot** [comment]
Thanks Nicolas, 

I'll take a look at that .coffee file.

Re: that pivot.js file.  Yes, that is the one.  If it's not too much of a hassle to give the line numbers, I think I'd rather try that route first.

Thanks again.

**Comment by nicolaskruchten** [comment]
OK, take the current lines 875-900 inclusive (i.e. the selected block here: https://github.com/nicolaskruchten/pivottable/blob/master/dist/pivot.js#L875-L900) and move them up to sit just below the current line 834.

It's a pretty simple change: you're taking the block that generates the totals row and moving it above the block that generates the main body of the table. If you want a totals row both above and below, then just copy it instead of moving it and you'll get both :)

**Comment by LukePivot** [comment]
You are the man, Nicolas! 

I hope to try this out tomorrow.  If not, I'll try early Monday and will let you know how it goes.

Thanks again for being so responsive.   I hope others get to appreciate this great library.  It really is amazing!

**Comment by LukePivot** [comment]
Nicolas:  this worked perfectly!  Thank you so much for the help.

Keep up the incredible work...

**Comment by nicolaskruchten** [comment]
Happy to help!

**Comment by LukePivot** [comment]
I always wished Excel had this option.  It's great your code is able to allow this without too much effort.

**Comment by rohantarai** [comment]
Hi @nicolaskruchten
Is the file updated? Because i see line 875-900 as below
```
if (rowKey.length === 0 && colKey.length === 0) {
          agg = this.allTotal;
        } else if (rowKey.length === 0) {
          agg = this.colTotals[flatColKey];
        } else if (colKey.length === 0) {
          agg = this.rowTotals[flatRowKey];
        } else {
          agg = this.tree[flatRowKey][flatColKey];
        }
        return agg != null ? agg : {
          value: (function() {
            return null;
          }),
          format: function() {
            return "";
          }
        };
      };

      return PivotData;

    })();
    $.pivotUtilities = {
      aggregatorTemplates: aggregatorTemplates,
      aggregators: aggregators,
      renderers: renderers,
```

Can you guide me from if this is what i need to move to line 834?
