### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by AmitGoutham** [nicolaskruchten/pivottable#379]
Hi,
When the error in the image appears , the table does't get rendered.When cache and browser history is cleared, the table is rendered but error remains. 

Any help will be appreciated.Thanks!
![capture](https://cloud.githubusercontent.com/assets/8773462/9408202/17b68842-482e-11e5-9c5b-42d9e66d24ce.PNG)

**Comment by nicolaskruchten** [comment]
This is basically the same as the issue you brought in #376 right? As I've said there, the issue seems to be due to other scripts you're running (like sap-ui-core.js or something like that)

Are you able to reproduce this problem with the example at http://nicolas.kruchten.com/pivottable/examples ? If not, I would tend to say that the issue comes from somewhere else in your page

**Comment by AmitGoutham** [comment]
Hi Nicolas,
In #376, the issue was about running my applications in different machines.
In #379 issue, the problem is rendering in the same machine.
My application does not throw this error when i do not use pivot.js. Also, i'm not able to reproduce the error with examples on your site.

**Comment by nicolaskruchten** [comment]
I'm unclear about how clearing browser history would apply to running an application on different machines...

**Comment by AmitGoutham** [comment]
Hi Nicolas,
The issue got resolved when i called .pivotUI inside setTimeout.
So..the issue was the rendering time and not cache!! :+1:

**Comment by nicolaskruchten** [comment]
Great! Does that resolve #376 also?

**Comment by AmitGoutham** [comment]
Yes!! #376 too is resolved! :+1:

**Comment by nicolaskruchten** [comment]
Super
