### ISSUE TITLE
Help in avoiding widget overlap

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolaskruchten/pivottable#397]
Taking into account that I'm fully aware of the issues you covered in your responses to issue #325 ,
I wonder if there is a way to resolve a problem I'm currently experiencing (using `rpivotTable`).

- I display the pivottable correctly on a page, together with  another widget just below.
- When I change renderer, say from Table to Treemap (increasign the size of the pivot table), I get the pivottable overlapping the widget below, as the pivot table has increased in size but the widget below hasn't been pushed down as a result.

The desired outcome of course would be to see the widget below dynamically pushed down the page so that there is no overlap.
So far I've played with different css settings but failed to achieve this result.

Could you kindly suggest a css setting that would eliminate the overlap?

Many thanks in advance

(if needed I can paste an example in R using rpivotTable)

**Comment by nicolaskruchten** [comment]
I would need an example of this to see what the problem is, as by default this is the behaviour: the pivot table itself is not using absolute positioning, so it should just flow with the page. For example, see http://nicolas.kruchten.com/mtl311/ where there is a pivot table with a footer below it, and no matter what you do to the pivot table, the footer is never overlapped.

**Comment by andineck** [comment]
my answer in #325  might help
