### ISSUE TITLE
Fixed Headers and the first column

### ISSUE THREAD

**Issue by psysai** [nicolaskruchten/pivottable#485]
Thanks for this amazing JS tool. I have a question and I am new to js and jquery, so some one can guide me. 

I am using the pivot table for a large set of data and the table was growing out of screen. I was able to enclose the table in a div and use overflows (only on the data table) to make scrolling possible. I am now trying hard to fix the headers and the first column, so that when the table is scrolled, they are always visible. Is there a way to do it? I tried this with CSS and I am just breaking the table. 

Thanks!

**Comment by nicolaskruchten** [comment]
I'm glad you like this library!

I don't know of any way to reliably do what you're looking for, unfortunately.

**Comment by VitaliyMF** [comment]
@psysai Several days ago I've released new version of the NReco pivottable.js extensions (this is non-intrusive add-on that adds some useful features - like "sort by click" or handling click on the values cells for drill-down functionality) that implements fixed headers both for columns and rows headers. You can try it online [here](http://webpivot.nrecosite.com/). These extensions have fully-functional free "community" version that can be used in commercial projects.

@nicolaskruchten unfortunately I cannot share fixed headers code and make it open-source because it was developed under commercial conditions. Nevertheless, I think it is better to have at least some alternative with NReco extensions than nothing.

**Comment by yannouchou** [comment]
FYI @psysai  I have implemented #509 precisely for that purpose, at least for header rows.
Now wrapped in a thead tag, the headers can be fixed using http://mkoryak.github.io/floatThead/ which I'm sure will do what you need (for rows).

**Comment by viraj12345** [comment]
> FYI @psysai I have implemented #509 precisely for that purpose, at least for header rows.
> Now wrapped in a thead tag, the headers can be fixed using http://mkoryak.github.io/floatThead/ which I'm sure will do what you need (for rows).

Can you please provide an example of how this was implemented with pivot table? I have been trying with no success so far...

**Comment by liudao008** [comment]
no success of my reason [var $table =$(".pvtTable")]  is not live 。i add button for fixed. it ok
$('#lbtnIce').click(function(){
        var $table =$(".pvtTable");
        // $table.on("floatThead", function(e, isFloated, $floatContainer){
        //     if(isFloated){
        //         $floatContainer.addClass("floated");
        //         $(this).addClass("floated");
        //     } else {
        //         $floatContainer.removeClass("floated");
        //         $(this).removeClass("floated");
        //     }
        // });
        // $(".floated").css("background-color","#d5ffd5");
        // if($(".pvtTable tbody th tr").length<2){
        //     $table.floatThead({
        //         headerCellSelector: 'tr>th:eq(0),tr>th:eq(1)'
        //     } );
        // }else{
        //     $table.floatThead({
        //         scrollContainer: function($table){
        //             return $table.closest('.wrapper');
        //         }
        //     });
        // }
    })

if you want to fixedColumns. could use jquery.fixedheadertable.js

**Comment by VitaliyMF** [comment]
@liudao008 does it (fixedHeaderTable plugin) work for pivot table row-labels (when there is a dimension(s) for rows)? Most likely this plugin, as well as 99% of another solutions for table fixed headers, works only for column labels - because it splits table into 2 parts, but this approach just not impossible for row labels and horizontal scroll.

True fixed headers should use another approach that keeps original <table> as is, and fixes only elements with labels and names of dimensions (top-left corner). You may check my comment above where I've mentioned solution for pivottable.js fixed headers that is based on 'position:sticky'.

**Comment by ValerioCietto** [comment]
> > FYI @psysai I have implemented #509 precisely for that purpose, at least for header rows.
> > Now wrapped in a thead tag, the headers can be fixed using http://mkoryak.github.io/floatThead/ which I'm sure will do what you need (for rows).
> 
> Can you please provide an example of how this was implemented with pivot table? I have been trying with no success so far...

Download floatThead.js, place it in "dist" folder.
Import floatthead always after jquery. 
`<script type="text/javascript" src="dist/jquery.floatThead.js"></script>`
And call floatThead always after the pivot table has been created like this:
`    $(document).ready(function(){
        setTimeout(function(){
            var $table = $('table.pvtTable');
            $table.floatThead();
        },3000);
    });` 
I don't know if there is a callback that is called when the table has been created, if so, floatThead has to be called just after.

**Comment by nokados** [comment]
In addition, there is an option for pivotUI:

`onRefresh: function(config) {$("table.pvtTable").floatThead();},`
