### ISSUE TITLE
Localization Issue

### ISSUE THREAD

**Issue by PhantomYdn** [nicolaskruchten/pivottable#490]
If locale is not 'en' pivotUI() leads to the following error:

```
pivot.coffee:772Uncaught TypeError: opts.aggregators[aggregator.val(...)] is not a function
```

And btw - how to localize fields themself? For example in json I have a, b and c. And I want to have that shown as "Localized name for A", "Localized name for B" and "Localized name for C". Is it possible?

**Comment by PhantomYdn** [comment]
After research I figured out a reason: configuration was prepared under one locale, but then tried to be used under another. Unfortunatly library is storing names localized - so it can't find it next time.
Is there some way to make configuration locale agnostic?

Also, as I can see pivot() is not recieving locale as an input parameter. Would be perfect to have it a long with pivotUI()

**Comment by nicolaskruchten** [comment]
This library doesn't touch the input data, so if your field is called `a` in the input JSON, it will be displayed as `a` always and never localized.

I don't understand your second comment about locale-agnosticism, you'll have to provide me with an example of the problem you're encountering...

**Comment by PhantomYdn** [comment]
Regarding 'a' and absence of ability to localize it. I think, it's real use case - even for single language. For example JSON might be optimized for size: so all field names a short, but in UI it might be needed to have longer version of a field. According to code: it shouldn't be hard: just to allow specify function for translation from 'a' to 'My Long Property A Name' or if function is not a case just JS object with key-values for field names.

Regarding locale agnostic. Use case is the following. I'm working on http://orienteer.org/. Project is using you brilliant library for showing pivottable. See demo: http://demo.orienteer.org/

* pivot() is used for showing pivot: http://demo.orienteer.org/browse/DemoPivotTable
* pivotUI() is used for configuration: try click gears on link above

So pivotUI() prepare configuration which than can be used by pivot()
And main problem is that configuration after pivotUI() does contain localized data: aggregatorName and rendererName which if being used "as-is" in pivot() lead to problems.

I have already worked out the situation by the following code: https://github.com/OrienteerDW/Orienteer/blob/master/orienteer-pivottable/src/main/resources/org/orienteer/pivottable/component/pivottable.tmpl.js
But that looks rather bad hack and I think it will be quite useful to have that reworked in the library themself.

**Comment by nicolaskruchten** [comment]
I don't think I agree regarding localizing data labels, I think this is a layering violation. PivotTable.js exists to display data, and labels are part of the data. If you really need to mutate the data, you can use the `derivedAttributes` and `hiddenAttributes` parameters to create copies and hide the originals on the fly, or you can preprocess the data before feeding it into PivotTable.js. If space is a consideration, you can use the compact array-of-arrays input format rather than the verbose array-of-objects format. The array-of-arrays format conveniently has all the labels in the first array, making it easy to translate the labels before calling PivotTable.js if that's what you want to do.

Regarding aggregator/deriver names and `pivot()` I think your approach is basically the way I would recommend doing this.

**Comment by PhantomYdn** [comment]
Transforming of names by hiddenAttributes/deliveredAttributes or by preprocessing is quite huge overhead. If you don't mind, I can prepare Pull  Request which will introduce new parameter to configuration: function for field names translation. By default it will use identical transformation. Are you OK with this proposal?

The problem with my implementation is in fact that it fully relly on order of items in localizations. That might be broken some day. But i didn't find other way how to link together different aggregators from different locales.

**Comment by nicolaskruchten** [comment]
I appreciate your offer of a pull request, but I don't think this is a feature which I am inclined to add to PivotTable.js at this time. It seems fairly specific to your use-case at the moment, and I'm resisting the addition of new parameters wherever possible.

**Comment by PhantomYdn** [comment]
That's sad. I'm 100% sure that I'm not alone: that should be quite common case. Lets do the following: I will create a new issue and if it will be needed for 5 people - that will be a sign:)

**Comment by PhantomYdn** [comment]
Done: issue #492.  

Just to close this issue. What do you think about this my statement?

> The problem with my implementation is in fact that it fully relly on order of items in localizations. That might be broken some day. But i didn't find other way how to link together different aggregators from different locales.

Do you see any better way to translate from one language to another without relaying to order?

**Comment by nicolaskruchten** [comment]
It may well be that you're not alone in wanting this feature, but in the 450 reported issues over the past 3 years you're the first to ask for it :) We'll see.

Regarding your last question: a better approach might be for your system to generate its own locale information on the fly based on a central registry where you maintain bidirectional mapping of names to entities like aggregators. You probably want to do that anyway to guarantee that you have consistent coverage of locale information for all of the entities you want to support: I accept PRs for language packs but not everyone translates every label and it's hard for me to do QA in languages I don't speak.

In general, I understand what you're trying to do but my take is that you're trying to push this library a bit beyond the scope of what it was designed for, so you're bumping up against the limits of the architecture. The existing localization setup was basically designed for simple 'one-time' localized displays of minimally-transformed data rather than to enable the generation of configurations in one locale which would then be stored and re-applied possibly in a different locale, while also translating labels within the input data.

At this point I consider this library to be fairly mature and stable, so while it may be possible to evolve the architecture to meet your needs, I'm reluctant to rock the boat very much in a way which would require me to re-work documentation, examples etc.

**Comment by PhantomYdn** [comment]
> At this point I consider this library to be fairly mature and stable, so while it may be possible to evolve the architecture to meet your needs, I'm reluctant to rock the boat very much in a way which would require me to re-work documentation, examples etc.

I do agree with you. But problem is that with matureness there are quite limited set of extension points... And according to number of [different forks here](https://github.com/nicolaskruchten/pivottable/network), people prefer to have their own version with exclusive feature which is needed for them. Please consider some ways to consolidate those huge number of different forks: imho some extention points in configuration might help a lot.

**Comment by nicolaskruchten** [comment]
I shall continue to consider it. From my perspective, this is actually a very small number of forks compared to the thousands of clones and downloads per month that I can observe.

**Comment by nicolaskruchten** [comment]
@PhantomYdn it occurs to me that the extension point you seek actually already exists! 

Under the hood, `pivot()` calls a Renderer and passes in a `PivotData` object. If you define a generic "chaining" Renderer which accepts the `PivotData` object, wraps it with your renaming functionality, and passes it along to whichever underlying Renderer you want to use, I believe this would meet your requirements. The underlying Renderer would call, say, `getRowKeys()` on the wrapped PivotData object, which would run the correspondance between your desired set of display labels and the underlying, 'compact' labels.

Wrapping a Renderer is pretty easy, it's analogous to the way the Heatmap Renderer is set up: https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L154

**Comment by starglad** [comment]
Well, I'm surprised that in 2 years no one needed it. I was trying to figure out what the issue was but finally I've come to this thread, where I could see that not having the "en" locale was the problem. I was using PT and was having the same issue. Thank you @PhantomYdn for the report

**Comment by edekk** [comment]
I am a bit of necromancer since this is an old thread, but someone might find it useful. I resolved the issue using @nicolaskruchten hint to map my aggregators and renderers on the fly. Then, when calling a restore function

`$("#output").pivotUI(response.data, JSON.parse($.cookie("pivotConfig")), true);`

I used previously created object of my aggregators and renderers:
```
const renderers = {
    "Tabela": $.pivotUtilities.renderers["Table"],
    "Wykres słupkowy w tabeli": $.pivotUtilities.renderers["Table Barchart"],
    "Mapa ciepła": $.pivotUtilities.renderers["Heatmap"],
    "Mapa ciepła wg. wiersza": $.pivotUtilities.renderers["Row Heatmap"],
    "Mapa ciepła wg. kolumny": $.pivotUtilities.renderers["Col Heatmap"],
    "Wykres słupkowy poziomy": $.pivotUtilities.plotly_renderers["Horizontal Bar Chart"],
    "Wykres słupkowy": $.pivotUtilities.plotly_renderers["Bar Chart"],
    "Skumulowany wykres słupkowy": $.pivotUtilities.plotly_renderers["Stacked Bar Chart"],
    "Wykres liniowy": $.pivotUtilities.plotly_renderers["Line Chart"],
    "Wykres warstwowy": $.pivotUtilities.plotly_renderers["Area Chart"],
    "Wykres rozproszony": $.pivotUtilities.plotly_renderers["Scatter Chart"],
    "Wykres kołowy": $.pivotUtilities.plotly_renderers["Pie Chart"],
};

const aggregators = {
    "Suma": $.pivotUtilities.aggregators['Sum'],
    "Srednia": $.pivotUtilities.aggregators['Average']
}

const ren_agg = {
    renderers: renderers,
    aggregators: aggregators
}
```
I changed restoring function into

`$("#output").pivotUI(response.data, {...config, ...ren_agg}, true);`

where

`const config = JSON.parse($.cookie("pivotConfig"))`
