### ISSUE TITLE
reduce x axis

### ISSUE THREAD

**Issue by stefanf1** [nicolaskruchten/pivottable#542]
Hi Nicholas, I understand that pivottable.js just a hobby, and that not much time, but if you find a few I'd like to help me. I use PivotTable.js to visualize not very large volumes of data (between 400 and 500 lines) in the line chart, but the x axis appears too much text (400-500 lines). I wonder if it is possible to reduce to about 5-10 lines. I read the page http://c3js.org/samples/axes_x_tick_culling.html, there is a way, but I do not know that it is possible and how. Thanks in advance for your help. I provide a picture of what I'm talking about
![untitled](https://cloud.githubusercontent.com/assets/21104993/17777372/0e89044e-6569-11e6-8f56-368a46e8200a.jpg)

**Comment by nicolaskruchten** [comment]
Sorry for the long delay in responding... The issue here is that your x axis is textual, rather than numeric, so C3 is just doing the obvious thing and showing all the labels. Any further C3-based processing you want to do is probably outside the scope of this library, and you would have to pass parameters through to C3 instead...
