### ISSUE TITLE
Usage inside ReactJS

### ISSUE THREAD

**Issue by aldemiraj** [nicolaskruchten/pivottable#558]
This is a fantastic implementation of pivot tables in js and I was wondering if it can be used with React.

I have read previous issues regarding the usage with AngularJS and I was wondering if anyone has tried using it inside React? How would it cooperate with the Virtual DOM?

**Comment by nicolaskruchten** [comment]
The virtual DOM would not be able to do much with this library, and you would have to force a re-render. You may want to use http://orbjs.net/ instead.

**Comment by nicolaskruchten** [comment]
Update: I have successfully used this library with React :)

**Comment by joncelay** [comment]
Would you mind sharing your integration?

**Comment by nicolaskruchten** [comment]
It's pretty trivial:
1. your `render` method renders a `<div id="output">`
2. somewhere else in your component's lifecycle hooks, like in your `componentDidUpdate` method, you call `$("#output").pivotUI( ... )`

**Comment by krazziekay** [comment]
I am trying to use this pivottable in my reactjs project. Firstly I installed jquery and this library using npm. Then, I am now trying to pivot a given data, and it seems that using $('....').pivot is working however $('....').pivotUI is not working, it gives an this error : 
![image](https://user-images.githubusercontent.com/13076255/27212453-d3854ce0-527f-11e7-93e5-08d765ab765d.png)
Can you please help me out!
Plus, when I am using $('....').pivot, the css is not showing up:
![image](https://user-images.githubusercontent.com/13076255/27212471-fe8d8f06-527f-11e7-8b57-fe2c4770e42c.png)

**Comment by nicolaskruchten** [comment]
You need jquery-ui as well :)

**Comment by nadim** [comment]
@nicolaskruchten First of all thank you so much for this pivot table.

I'm trying this out with react right now and it feels like a bit of a hack... separately telling the pivottable to render in componentDid(Mount|Update). Also I've been trying to avoid including jQuery but for this pivottable i'm making an exception. Is this the way you see this all working for the forseeable future?

Thank you,

+Nadim

**Comment by nicolaskruchten** [comment]
@nadim it is a bit of a hack, but it's pretty justified in this case because every time you change anything in the input, the whole table gets thrown away and redrawn, so I doubt that React's virtual DOM adds any value here. 

I've thought about rewriting this library in React but I just haven't had/likely won't have the time to manage what would effectively be a fork, and in any case I've been moving away from React towards Mithril in my own projects :)

**Comment by nadim** [comment]
great thank you for the response and useful info about the redraw behaviour.

**Comment by timelyportfolio** [comment]
I experienced the same `pivot` working and `pivotUI` not working when I tried using `pivottable` with the slim build of jQuery  3.x.  Here are the [lines](https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L709-L712) that cause the first error/failure.  I am assuming this is caused by the deprecation of `bind` (see [http://api.jquery.com/bind/]), and that the slim build does not include deprecated functions.  Using the full `3,2.1` build of jQuery, `pivottable` still worked great.

**Comment by kurtzace** [comment]
This is how you utilize pivottable within reactjs https://github.com/kurtzace/pivottableandreact

**Comment by nicolaskruchten** [comment]
@kurtzace thanks for sharing!

I should note that I've recently been hired to create an official React-only (no jQuery) port of this library, and the work is underway here: https://github.com/plotly/react-pivottable

I expect a working release sometime in October, as I'm only working on this 1 day/week at the moment.

**Comment by nicolaskruchten** [comment]
If anyone wants to give feedback on the React port, I would greatly appreciate it! It's available here https://react-pivottable.js.org/ :)

**Comment by nicolaskruchten** [comment]
It's very close to being released, maybe a week!
