### ISSUE TITLE
run pivotui() but nothing shows up

### ISSUE THREAD

**Issue by Chandlerwu007** [nicolaskruchten/pivottable#607]

**Comment by rickFanta** [comment]
Hiya Nicolas,
First of all, great product and excellent presentation on the Montreal city data.  It's dropping the jaws of everyone that I show it to.  Major kudos, my friend.

Hey, similar to the above, I'm finding that jupyter launches pivots on my laptop just fine, but am having issues at work.  [On the latter, I'm behind a firewall and also running on a vmware instance in stand-alone/non-bridged mode.  The proxy settings seem to be fine otherwise, and I even set HTTP_PROXY and HTTPS_PROXY environment vars for anaconda to pickup automatically as well as setting ssl_verify to False.]  The pandas dataframes load just fine, but I'm not seeing anything in the cell where I try to display a pivot_ui using even the simple examples that you've provided.

I've even started jupyter with --debug and looked at the logs, but don't see what's going on yet.  Any suggestions for how to debug this?

Much obliged for your indulgence on this, and all your fine efforts.
Rick

**Comment by nicolaskruchten** [comment]
Ahhh you're referring to the Jupyter integration... In general I prefer for those issues to be referred to that project's repository i.e. https://github.com/nicolaskruchten/jupyter_pivottablejs ... are you able to open an issue there and I'll help you debug things?

**Comment by nicolaskruchten** [comment]
(also, thanks for the kudos :)

**Comment by rickFanta** [comment]
Done.  Thanks a lot.  I know that using Chrome debugging extensions to isolate the issue at a particular javascript line would help, but have run into some install issues there too today and haven't solved yet.

**Comment by rickFanta** [comment]
Hiya.  The jupyter issue is filed here; https://github.com/nicolaskruchten/jupyter_pivottablejs/issues/19
