### ISSUE TITLE
how can i use pivottablejs in spyder

### ISSUE THREAD

**Issue by slrosssss** [nicolaskruchten/pivottable#711]
import pivottablejs
pivottablejs.pivot_ui(pd.DataFrame([12,2,3]))
Out[1]: <IPython.lib.display.IFrame at 0x22736104f28>

no plot shows

**Comment by nicolaskruchten** [comment]
A couple of things:
1. It seems like you're using `jupyter_pivottablejs` which is not hosted in this repo but rather https://github.com/nicolaskruchten/jupyter_pivottablejs so that would be the place to report issues, not here
2. Can you give me more details about your setup? I'm not familiar with Spyder, and `jupyter_pivottablejs` has only been tested in standard Jupyter

**Comment by slrosssss** [comment]
1:Yes,the code is running on spyder
2:windwos10 64bit ; winpython(the same as Anaconda);
I tried all versions Spyder (python2.7 32bit, python3.5 64bit, python 3.5 32bit) but no works, My colleagues and i use Spyder becuase it's more suitatble for data mining, So thank you for sharing a great tool!

**Comment by nicolaskruchten** [comment]
Does Spyder have a Jupyter component to it? `jupyter_pivottablejs` is specifically designed to work with Jupyter, not Spyder.

**Comment by slrosssss** [comment]
I see..Spyder did not have a Jupyter component
Thank you very much
