### ISSUE TITLE
Labels for Columns and Rows different from Data?

### ISSUE THREAD

**Issue by raffaelmeier** [nicolaskruchten/pivottable#718]
I have a big problem where I really stuck.
My data looks like this at the moment:
![2017-05-27_14-07-33](https://cloud.githubusercontent.com/assets/28999979/26521347/dbf69d8c-42e6-11e7-95d6-b80048b74f36.jpg)

My issue is, that I would like to show the user meaningful "text" labels instead of just the numbers like here:
![2017-05-27_14-06-57](https://cloud.githubusercontent.com/assets/28999979/26521349/e96e00f4-42e6-11e7-9524-201d0ff1897b.jpg)

but I can not change the data material, because then, aggregate functions can not be computed, right? I mean, when I change all the 1 to "a lot", all the 2 to "a bit", etc. - then I can not average the data to e.g. 2,34 as a average of all the 1, 2, 3 and 4s... because it's text ("a log", "a bit"... have no arithmetic average, no sum etc.)

Who can I "translate" only the colum and row labels to text without changing the data?
Is there a possibility?

**Comment by nicolaskruchten** [comment]
In general, one doesn't encounter this problem all that often, because most fields are either used in the rows/columns OR as the input to an aggregator, but rarely both. There is no way to remap things within the library so if you really need to do what you're trying to do, you will likely need to to your input add a second copy of your numerical data columns containing the strings you're looking for. The `derivedAttributes` parameter might be of use here :)
