### ISSUE TITLE
TSV Export Missing Totals

### ISSUE THREAD

**Issue by mreishus** [nicolaskruchten/pivottable#730]
Using http://nicolas.kruchten.com/pivottable/examples/mps_export.html and switching between the "Table" and "TSV Export" views, the Export is missing the total column and row.  Is there a way to specify this should be shown?

**Comment by 01** [comment]
If I am not mistaken, since total column and row is aggregated by the pivotJS library and export_renderer simply takes the the data outputs it as a TSV given data given the aggregator. Its a simple fix if you look at the export_renderer.js while its looping through rows or columns keep sum, and at end of loop push it row/column respectively.

**Comment by nicolaskruchten** [comment]
It's not hard, but I'm pretty sure there was a reason why I didn't do this at the outset. I'll need to dig into it to remember why not :)

**Comment by 01** [comment]
Nicolas, I would image why you wouldn't do that as they are not data points and are simply aggregations of the whole. When exporting it trying to use that data for graphing/charting or even feeding it back into Pivot library would mess up the data as no way to distinguish it as a summation and not a data point.

**Comment by nicolaskruchten** [comment]
@01 that seems about right!

**Comment by buruno** [comment]
I stumbled upon this and wrote a gist, if anyone else needs it: https://git.io/vpywu
