### ISSUE TITLE
Page unresponsive for large local CSV input.

### ISSUE THREAD

**Issue by WSAyan** [nicolaskruchten/pivottable#775]
Hi
I am having trouble with my browser with this csv file https://www.dropbox.com/s/coqryr8vskfghtb/TransactionTrendForPivotJS_2007.csv?dl=0
which contains almost 75881 rows of data. Script stops responding while trying to drag some columns. What may cause this problem. Is there nay data limitation to display columns properly? Or is this a browser issue? 
### Screenshot: 
![pivot](https://user-images.githubusercontent.com/7785995/30248216-5ed264dc-9645-11e7-9eaf-b3d40c0ae000.PNG)

**Comment by nicolaskruchten** [comment]
I suspect the issue is less with the input size (which is large-ish but not prohibitive) and more with the output size... based on the screenshot, you are trying to create multiple rows per transaction, and then date-based columns, which leads to a giant table with millions of cells. This is poorly supported by browsers in general.

**Comment by WSAyan** [comment]
What I am trying now is to connect to a report server and show data directly from servers. So the data can be very large. And user can be very playful with columns. Is there any work around to visualize data in smaller chunks?

**Comment by nicolaskruchten** [comment]
There's no way to render only part of the output, no. You can use the new `hiddenFromDragDrop` parameter to prevent users from using extremely-high-cardinality attributes in the table though.

**Comment by hkbeer** [comment]
Looking at screen shot. It is simply not right to pull value fields to the left column as row fields. Please draw it the other way

**Comment by WSAyan** [comment]
@hkbeer 
Unfortunately my users can do pretty much anything with the fields.

**Comment by hkbeer** [comment]
One way to solve it is to hide the value fields from the drop-area

**Comment by hkbeer** [comment]
"What I am trying now is to connect to a report server and show data directly from servers. So the data can be very large. And user can be very playful with columns. Is there any work around to visualize data in smaller chunks?"

Since you have server code control, if I am you I would narrow down the data on server side before rendering or passing to PivotUi. So you may aggregate the data first using SQL etc before pulling the data into the pivotUi. This is also what I am doing now.

**Comment by VitaliyMF** [comment]
> Unfortunately my users can do pretty much anything with the fields.

In this case pure js-only pivot table solution is not suitable for you... the problem of large pivot table can be solved with server-side pagination (or reasonable top-N limits for rows/columns) but you need some backend for this. 

Several years ago we also started with pivottable.js but found a lot of limitations related to dataset size - they come from the fact that all data and rendering are performed on the client-side. As result we created alternative solution that can be used for pivot tables generation even for big data (with ROLAP approach). I'm not providing the link as it is commercial product ( @nicolaskruchten let me know if it is ok to mention the product ).

**Comment by nicolaskruchten** [comment]
@VitaliyMF I have no problem with people mentioning alternatives :)

**Comment by WSAyan** [comment]
Well, I've failed to convince my company to build their own data visualization solution. They have moved to PowerBI which is a huge blow for me. Thanks for your suggestion @VitalilyMF
