### ISSUE TITLE
How to use Scatter Chart

### ISSUE THREAD

**Issue by hkbeer** [nicolaskruchten/pivottable#783]
My source table has 3 columns:
Country, Product, Revenue
How to select so Scattered Chart shows up something. I am using PivotUI
I choose Integer Sum on Revenue, and Country on left and Revenue on Top.
I then Choose Scattered Chart nothing show up
No matter how I arrange the fields it is still blank or just spots line up on a VERTICAL line instead of a line with slope.....

In my case, how do I arrange so the Scattered Chart would show up as a sloping line as expected ?

On investigation, It is picking up the field I dragged to the top and showing up on X-axis so it is fine. 
However,  seems the Y-axis is not picking up the fields that I dragged to the Left panel.
Is there anything I did wrongly ?

Please help... thanks

**Comment by nicolaskruchten** [comment]
the x-axis field goes across the top in the column area and the y-axis field goes down the side in the row area.

**Comment by hkbeer** [comment]
Thank you. So how should I arrange given Country, Product and Revenue($) ?

**Comment by nicolaskruchten** [comment]
A scatter chart requires two continuous variables. Country and Product are not continuous, they are categorical, so you cannot make a scatterplot with only those three.

**Comment by nicolaskruchten** [comment]
@hkbeer I should note that it's quite irritating that you submit issues with one title and body, and then you edit the title and body to be something completely different. When you submit an issue, I get an email with the original title and description, but after I think about it and click on the link, I land on a completely different issue!

For example, the original title of this issue was `How to allow multiple items in filter preload` and the original body was:

```
I am using this option to pre-filter the report
filter: function (row) {return row["Name"] == ["Name2"]; },

How to modify it to have multiple item filter so that only
Name2, Name 21, Name32 are shown and not the others ?

I tried
filter: function (row) {return row["Name"] == ["Name2", "Name21","Name32"]; },
It does not work....
Pls help... Thanks
```

If you want to continue requesting so much assistance with this library, I would ask that you please be a better Github Issues citizen and try to keep to "one issue, one question".

Thanks.

**Comment by hkbeer** [comment]
So sorry. Becoz I found solution of the original one be4 any reply and then a new help need comes up.  From now on I will not change the title and will start a new one for another request. I m new to Github so dunno much of its workflow be4 now. 

Thanks

**Comment by hkbeer** [comment]
I now pull 2 numeric fields to x y and it works. Thanks
