### ISSUE TITLE
Automatically breaking dates into weeks/months/quarters/years

### ISSUE THREAD

**Issue by jovenden** [nicolaskruchten/pivottable#790]
Hi I found this older request / conversation from around 3 years ago

> Group dates to weeks, monts, Quarters and Years #212 

Would we still need to code something specific ourselves or is there some native support for it?

thanks & all the best
Jeremy

**Comment by nicolaskruchten** [comment]
You still need to code an application-specific thing yourself :)

**Comment by jovenden** [comment]
Aaaw shucks!

Is your advice on this the same as it was on issue 212 or have approaches moved on since then?

**Comment by nicolaskruchten** [comment]
Yep! The reason this isn't automated is just because there are so many possible formats of inputs and outputs that people might need that I wasn't able to build a robust feature-set around it. If you don't mind pulling in another library you can also use Moment.js to build derived attributes which might have some fancier parsing/formatting options.

**Comment by hkbeer** [comment]
I think there is a option to convert dates into month, year as I am using it....

**Comment by hkbeer** [comment]
and as nicolas said we can customise. Quarter is easiler as %n is already giving us months... quarter can be derived from months so can be handled within pivot.js by adding If then.... 

For more complex case need to goto Moment.js.

**Comment by jovenden** [comment]
Just wanted to say "thank you" both for your comments; we will look into these approaches.
