### ISSUE TITLE
Datatable.net integration feasibility

### ISSUE THREAD

**Issue by mathieu-veron** [nicolaskruchten/pivottable#813]
Hello,
for pivot() (not pivotUI) datatable.net rendering is almost possible, 
the only thing blocking is the colspan/rowspan of the headers, because the number of column in the header do not match the number of col in the data.

refactoring the headers to be able to have at least one non empty cell in the tbody for each cell in the thead leads to a working/ filterable/sortable pivot result,
here a jsfiddle with some tweak of the headers demonstrating it working :
https://jsfiddle.net/MVTeraflop/kn381h7s/1188/

I was wondering, if it could be possible to add a default renderer compatible with datatable
in order to produce multilevel headers like in this example 
 :https://datatables.net/examples/advanced_init/complex_header.html

**Comment by nicolaskruchten** [comment]
A couple of responses:

1. You're welcome to create a renderer that meets your needs and then we can discuss the idea of integrating it or a generalized version into the main library when I get a sense of what it might look like. I don't have any time to devote to building one myself, and I don't think I would want to modify the default TableRenderer at this time.
2. Does DataTables support multilevel *row* headers as well as column headers? If not, then special handling will be required for when the renderer encounters multiple row attributes. In the past I have found data-grid-type components to be a poor fit for a PivotTable.js renderer because they are very column-oriented whereas the pivot table is symmetric in its treatment of rows and columns.

**Comment by mathieu-veron** [comment]
Hi, thx for the quick answer

> when I get a sense of what it might look like.
you can click on the 'tb2 to datatable' on my fiddle for a first idea https://jsfiddle.net/MVTeraflop/kn381h7s/1188/

You are right for the "very column oriented" of table, but in static reports, it works most of the time
like here : http://rwjblue.github.io/pivot.js/ 
(do not hesitate to add row by clicking on row label fields)

I will try creating a new renderer for  my project to deals with those extra rowspan and colspan.

**Comment by Ashlesha26shopti** [comment]
> Hi, thx for the quick answer
> 
> > when I get a sense of what it might look like.
> > you can click on the 'tb2 to datatable' on my fiddle for a first idea https://jsfiddle.net/MVTeraflop/kn381h7s/1188/
> 
> You are right for the "very column oriented" of table, but in static reports, it works most of the time
> like here : http://rwjblue.github.io/pivot.js/
> (do not hesitate to add row by clicking on row label fields)
> 
> I will try creating a new renderer for my project to deals with those extra rowspan and colspan.

Hi,

I had a similar use case. Were you able to solve this issue. 
I am also trying to incorporate datatable.net and PivotUI.
