### ISSUE TITLE
I can't deploy the pivottable react component on the apache server.

### ISSUE THREAD

**Issue by jakub0225** [nicolaskruchten/pivottable#837]
I tried to use the pivottable react component on the apache server. But I don't know how.
Please help me.

**Comment by nicolaskruchten** [comment]
Hi!

A couple of responses:

1. If you have questions regarding react-pivottable, please create issues in that repo (https://github.com/plotly/react-pivottable/issues) rather than here, otherwise it's very confusing for everyone...
2. I will need a lot more detail about what you're wanting to do, what you tried and how it went wrong, in order to help you :)

**Comment by nicolaskruchten** [comment]
Issue created here: https://github.com/plotly/react-pivottable/issues/6
