### ISSUE TITLE
how to display higher precision

### ISSUE THREAD

**Issue by jae-stats** [nicolaskruchten/pivottable#882]
The dataframe I'm using to pivot has numeric values showing up to 3 decimals places, but when I generate a pivot table using pivot_ui(), the numbers are rounded down to 2 decimal places, which is showing the mean as different to the reference I'm comparing to.
Is there a way to change the precision in pivot_ui()?

**Comment by nicolaskruchten** [comment]
I assume you're using https://github.com/nicolaskruchten/jupyter_pivottablejs here? If so, in future, please submit questions there rather than here so I can keep things straight :)

To answer your question, unfortunately there is no way to arbitrarily change the locale information (which controls number formatting) through the Python layer.

**Comment by jae-stats** [comment]
Oops, sorry! 
I realised I was being silly, changing to TSV export mode displays the full precision.
Thanks

**Comment by nicolaskruchten** [comment]
No worries. Glad you have a workaround, and sorry it's not more flexible!
