### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dv336699** [nicolaskruchten/pivottable#91]
Hi, first awesome work you did.

I was able to translate many of the texts, but the aggregators cannot be translated ATM.
My question is, are you planning to allow the component to be localized?
If yes, would you accept a PR in case I start localizing it?

Thank you

**Comment by ryvkin** [comment]
Hi, @nicolaskruchten

I would need to change numberFormat option in my project, digitsAfterDecimal. Found an example [here](https://jsfiddle.net/w86bgq9o/183/), it works fine "as is" for pivot() but this option does not have affect for pivotUI(). Could you recommend way out?

**Comment by nicolaskruchten** [comment]
For `pivotUI()` you will need to use something like `var sumAggregator = sum(floatFormat);` instead of `var sumAggregator = sum(floatFormat)(['tip'])` (in keeping with the example you linked).

See details here: https://github.com/nicolaskruchten/pivottable/wiki/Aggregators#built-in-aggregators-and-aggregator-templates
